services:
  - type: web
    name: abhimithra-portfolio
    runtime: static
    buildCommand: echo "No build step"
    staticPublishPath: ./public
    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=3600
